name: Docker CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          - name: Build builder for amd64 and arm64
            run: |
              docker buildx build --output "type=docker,push=false,name=pojntfx/go-binary-builder-amd64:latest,dest=/tmp/go-binary-builder-amd64" --platform linux/amd64 .
              docker buildx build --output "type=docker,push=false,name=jakwai01/n2n-binary-builder-arm64:latest,dest=/tmp/n2n-binary-builder-arm64" --platform linux/arm64 .
          - name: Build for amd64
            run: |
              docker load -i /tmp/n2n-binary-builder-amd64
              docker run --name n2n-binary-builder-amd64 -v ${PWD}:/data:z jakwai01/n2n-binary-builder-amd64:latest
          - name: Build for arm64
            run: |
              docker load -i /tmp/n2n-binary-builder-arm64
              docker run --name n2n-binary-builder-arm64 -v ${PWD}:/data:z jakwai01/n2n-binary-builder-arm64:latest
          - name: Publish binaries to GitHub releases
            if: ${{ github.ref == 'refs/heads/main' }}
            uses: marvinpinto/action-automatic-releases@latest
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "latest"
              prerelease: false
              files: |
                staging/*